### ISSUE TITLE
Exceptions used to create ErrorHeader needs to be accessible

### ISSUE THREAD

**Issue by quidryan** [Netflix/msl#84] opened 2016-03-07 23:14 UTC
MslControl converts exceptions (via MessageBuilder.createErrorResponse) into a ErrorHeader and passes that to MessageDebugContext. Those exceptions have very valuable information for logging and diagnostics purposes. I would like the exception to be passed class that outside implementations control, like how MessageDebugContext is provided to MSL and can log headers. It could even be a new call on MessageDebugContext (which could be added a Java 8 default method on the interface), e.g. MessageDebugContext.exceptionFound(Exception). Or  as a second parameter to sendHeader, but that's awkward if there is header is a MessageHeader. Maybe MessageDebugContext, should be refactored to have a sentMessageHeader(MessageHeader) and a sentErrorHeader(ErrorHeader, Throwable). This would make it easier for implementors too, since we wouldn't have to do an instance of on the Header and do the delegation ourself.

**Comment by wmiaw** [comment] 2016-03-10 19:13
I don't really understand what you're asking for. All MslExceptions are thrown back out to the caller already. You get them. You don't need a new function to access them and you don't need to parse ErrorHeaders to figure out what went wrong.

**Comment by quidryan** [comment] 2016-03-11 20:35
Are you thinking that we should look at MslControl.request's Future for exceptions? I believe it will throw an ExecutionException. So the contract with caller is to look at the cause of the ExecutionException and look for a MslException? If so, the docs could be improved, since they it says the Future will throw a MslException direction.

**Comment by wmiaw** [comment] 2016-03-11 21:36
Yes, look at the cause of the thrown ExecutionException. The documentation doesn't explicitly say this right now since by definition a Future can only throw an ExecutionException or an InterruptedException, but it can be made clearer like you said so I've opened issue #89.

**Comment by wmiaw** [comment] 2016-03-17 21:50
Closing since the exceptions can already be accessed.

**Comment by quidryan** [comment] 2016-03-30 17:51
I agree that exceptions can be handled by the caller, but I'm asking for a hook so that I can provide general solution to my implementations. Specifically I asked for the exception to be passed to MessageDebugContext which is a class that I already provide to my implementations, it is meant for debugging a message. MessageDebugContext receives the ErrorHeader but that that isn't adequate to debug a message's error.

If I can't hook into MSL to log exceptions, each system has to look for the exceptions coming out of the Future and call my logging function. They should be looking at the exceptions already, but that's to react to the exception, I don't want to conflate the behavior of reacting to an exception and the simple act of logging. Currently my only option to ask that each call my logging function ("please, pretty please") or put some abstract over MSL to be centrally log these exceptions. I don't think an abstraction over MslControl should be needed to centrally log exceptions. 

The framework should make it possible to log exceptions via a MSL provided hook/callback.

**Comment by wmiaw** [comment] 2016-03-30 18:09
Are you planning to implement an abstraction over MessageContext, and then require applications to use your MessageContext implementation, in order to centrally log exceptions? Versus requiring applications to use your MslControl abstraction in order to centrally log exceptions?

netflix-msl-library was originally envisioned as an abstraction over the MSL stack that would be used by all Netflix applications, instead of using the MSL stack directly, and this also matches the design for the MSL Auth service.

Also, an application that gets a MslException inside an ExecutionException from the Future will not be reacting in any way other than potentially to log the exception. The response will already have been sent. But unless you also require all applications to also make sure the response gets sent out from the OutputStream you will also want an abstraction over MslControl in order to provide that functionality by default.

**Comment by wmiaw** [comment] 2016-05-02 20:15
* If you want to see every MslException thrown, looking at only the error responses that go out will not show you all of them because there are situations where an exception is handled or bypassed.
* If you want to see every MslException thrown that results in an error response being sent, looking only at the MslException inside the ExecutionException that is thrown to the calling application will not show you all of them because MSL is self-healing and establishing communication may require multiple messages and round trips.
* If you want to see every MslException thrown that would result in an error response being sent, looking at only the error responses being sent will not show you all of them because an error response will not be sent if the max message count has been hit.

The three top-level locations that can provide insight are the MessageDebugContext, MessageRegistry, and ExecutionExceptions thrown from MslControl APIs. The better place to log things is inside individual classes provided by the application's MSL configuration because that is the only place where the exception is guaranteed to exist and will not get swallowed up by MSL core logic.

**Closed by wmiaw** 2016-05-02 20:15 UTC
Labels: enhancement
